import { Geist, Geist_Mono } from "next/font/google";
import Iridescence from "@/components/Background";


import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "look behind you! 👻",
    description: "Generated by GOD",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}>
                {/* <Background /> */}
                <Iridescence color={[0.8, 0.8, 0.8]} mouseReact={false} amplitude={0.1} speed={1.0} />
                {children}
                
            </body>
        </html>
    );
}
