import { Geist, Geist_Mono } from "next/font/google";
import Background from "@/components/Background";

import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "look behind you! 👻",
    description: "Generated by GOD",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden `}
            >
                <Background />
                {children}
            </body>
        </html>
    );
}
